# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='photoPath',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
