# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_company_photopath'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=200)),
                ('photo', models.ImageField(max_length=500, upload_to='/Users/Gmurr/IdeaProjects/CS242/Final0/myApp/static/')),
                ('photoPath', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
