# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(max_length=500, upload_to='/Users/Gmurr/IdeaProjects/CS242/Final0/myApp/static/uploadedImages/')),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('index', models.IntegerField(blank=True)),
                ('photoPath', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
