# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='index',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photoPath',
        ),
    ]
