# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default='this is a description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(max_length=500, upload_to='/Users/Gmurr/IdeaProjects/CS242/Final0/myApp/static/blogPhotos/'),
        ),
    ]
